### ISSUE TITLE
Dúvida - Ligação à base dados através de JDBC

### ISSUE THREAD

**Issue by parreirinha** [isel-leic-daw/1920v-public#1]
Bom dia.

Estou a ter dificuldade a ligar a minha base de dados postgres através do jdbc e como tinha duvidas do canal a utilizar vou colocar aqui a minha questão pois assim alguém que tenha passado pelo mesmo erro pode responder ou ajudar alguém que o venha a ter.

-  primeiro adicionei uma classe onde crio a connection

`private final String url = "jdbc:postgresql://localhost:5432/daw";`
`private final String user = "postgres";`
`private final String password = "isel";`
`Class.forName("org.postgres.Driver");`
`conn = DriverManager.getConnection(url, user, password);`

- de seguida no `Project Structure` adiciono no separador `Libraries` o seguinte jar:

`postgresql-42.2.11.jar` que é o driver da versão que tenho instalado. 

- Por fim no ficheiro `build.gradle` adiciono às dependências `compile(group: 'org.postgresql', name: 'postgresql', version: '42.2.11')`

o erro apresentado  é: `org.postgres.Driver`

**Comment by pmhsfelix** [comment]
- Basta adicionar a dependência ao `build.gradle` e depois sincronizar o projecto IntelliJ com o `build.gradle`.
- Use um data source em vez de usar o `DriverManager.getConnection`, tal como fizemos em LS.

Por favor abra de novo o issue se a questão persistir.
