### ISSUE TITLE
Repositórios

### ISSUE THREAD

**Issue by Caldeiradas** [isel-leic-daw/1920v-public#3]
Boa tarde engenheiro  

Lamento a demora na leitura da mensagem de 28 de Março mas não tenho nenhum e-mail de confirmação ou pedido de entrada em repositórios.

Continuação de bom dia e boa semana

Gonçalo Caldeira, a41465

**Comment by pmhsfelix** [comment]
- Já verificou se a mensagem não está numa pasta de "spam"?
- Verifique se tem acesso ao repositório.

Reabra este "issue" caso o problema continue por resolver.
